/**
 * Core game-engine types.
 *
 * Golden rule: no identifier here may reveal the case solution. IDs are opaque
 * and stable (CLUE_0xx, EVENT_0xx, LOCK_00x, MEMORY_0xx).
 */

export type ActNumber = 1 | 2 | 3 | 4;
export type Difficulty = "normal" | "hard";

export type AppId =
  | "APP_001" // Notifications
  | "APP_002" // Vínculo (chat)
  | "APP_003" // Gallery
  | "APP_004" // Mail
  | "APP_005" // Contacts
  | "APP_006" // Calendar
  | "APP_007" // Órbita (browser)
  | "APP_008" // Phone
  | "APP_009" // Voz Segura
  | "APP_010" // Bloco (notes)
  | "APP_011" // Rumo (maps)
  | "APP_012" // Nimbo Drive
  | "APP_013" // Recovered
  | "APP_014" // Pulso (health)
  | "APP_015" // Banco Aurora
  | "APP_016" // Vello
  | "APP_017" // Fluxo
  | "APP_018" // Chave
  | "APP_019" // Feito
  | "APP_020" // Settings
  | "APP_021"; // Case Notebook

export type LockId =
  | "LOCK_001"
  | "LOCK_002"
  | "LOCK_003"
  | "LOCK_004"
  | "LOCK_005"
  | "LOCK_006"
  | "LOCK_007"
  | "LOCK_008"
  | "LOCK_009";

export type CharacterId = "CHAR_002" | "CHAR_003" | "CHAR_004" | "CHAR_005";

export type ClueId = string;
export type EventId = string;
export type MemoryId = string;
export type PhotoId = string;
export type VoiceId = string;
export type VideoId = string;

/** Timed transcript line used by recordings and videos. */
export type TranscriptLine = { t: string; who?: string; text: string };

export type ClueWeight = 1 | 2 | 3 | 4;
export type ClueKind = "fato" | "testemunhal" | "inferencial" | "falsa";

export type Clue = {
  id: ClueId;
  /** Short label displayed in the notebook. */
  label: string;
  /** Neutral description of what the clue shows. */
  summary: string;
  app: AppId;
  act: ActNumber;
  kind: ClueKind;
  weight: ClueWeight;
  /** Evidentiary blocks used in the accusation: A (presence), B (time), C (motive). */
  block?: "A" | "B" | "C";
  /** Corresponding English fact, injected into AI only when allowed. */
  factEN?: string;
};

export type Memory = {
  id: MemoryId;
  label: string;
  text: string;
  /** Requires at least N of these clues to have been examined. */
  requiresAnyOf?: ClueId[];
  requiresCount?: number;
  requiresAllOf?: ClueId[];
};

export type LockKind = "pin" | "palavra" | "pergunta";

export type Lock = {
  id: LockId;
  kind: LockKind;
  /** Field label. */
  prompt: string;
  /** Hint written by Clara herself, always visible. */
  hint: string;
  /** Expected length, used only to inform the numeric keypad. */
  length?: number;
  /** Optional second factor (authenticator code). */
  secondFactorPrompt?: string;
  /** Previous-attempt log displayed before unlocking. */
  priorAttempts?: string;
  /** Accepts these already-normalized answers. */
  accepts: string[];
  secondFactorAccepts?: string[];
  /** Clues released when opened. */
  grantsClues?: ClueId[];
  /** Apps or areas released when opened. */
  unlocksApps?: AppId[];
};

export type PhoneAppDescriptor = {
  id: AppId;
  name: string;
  /** lucide-react icon name. */
  icon: string;
  /** Earliest act in which the app appears on the home screen. */
  availableFrom: ActNumber;
  /** Icon accent color. */
  tone: "verde" | "azul" | "ambar" | "rosa" | "cinza" | "roxo";
  /** Short text displayed below the icon when something is new. */
  subtitle?: string;
  /** Lock protecting the entire app. */
  lock?: LockId;
};

export type ChatRole = "player" | "character" | "system";

export type ChatMessage = {
  id: string;
  role: ChatRole;
  text: string;
  at: string;
  /** Clue attached by the player to this message. */
  clueId?: ClueId;
  /** Marks canonical lines not generated by AI. */
  scripted?: boolean;
};

export type ChatState = {
  messages: ChatMessage[];
  /** IDs of facts already released to this character. */
  disclosed: string[];
  /** Canonical beats already triggered. */
  beats: string[];
  /** Clues the player has already presented to this character. */
  presented: ClueId[];
  /** Intents already detected in this conversation. */
  intents: string[];
  /** Temporary lock (narrative silence) in epoch milliseconds. */
  silentUntil?: number;
  collapsed?: boolean;
};

export type AccusationDraft = {
  responsavel?: string;
};

export type AccusationAttempt = {
  at: string;
  outcome: "aceita" | "parcial" | "rejeitada";
  feedbackId: string;
};

export type Preferences = {
  reducedMotion: boolean;
  largeText: boolean;
  sound: boolean;
  locale: import("../locales/types").LocaleId;
  localeChosen: boolean;
  lastApp?: AppId;
};

export type GameState = {
  saveVersion: number;
  difficulty: Difficulty;
  /** Chosen before turning on the device and changed only by restarting. */
  difficultyChosen: boolean;
  act: ActNumber;
  /** Device already unlocked with the screen PIN. */
  phoneUnlocked: boolean;
  unlockedApps: AppId[];
  solvedLocks: LockId[];
  lockAttempts: Record<string, number>;
  cluesFound: ClueId[];
  cluesExamined: ClueId[];
  memories: MemoryId[];
  eventsFired: EventId[];
  chats: Record<string, ChatState>;
  /** Knowledge shared between CHAR_004 and CHAR_005 (the same person). */
  sharedLeak: string[];
  unknownEntered: boolean;
  /** Whether the player opened the anonymous contact chat; controls the icon badge. */
  unknownRead: boolean;
  /** Tracks which window is "typing"—never two at once. */
  typingLock?: CharacterId;
  notificationsSeen: string[];
  zoomed: PhotoId[];
  playedVoices: VoiceId[];
  playedVideos: VideoId[];
  accusation: AccusationDraft;
  accusationAttempts: AccusationAttempt[];
  hintsUsed: Record<string, number>;
  metaAttempts: number;
  revealShown: boolean;
  sentAudioToDiego: boolean;
  startedAt: string;
  lastSavedAt: string;
  /** Timestamp for entering the current act, used by anti-blocking fallbacks. */
  actEnteredAt: number;
};

export type GameAction =
  | { type: "RESTORE"; state: GameState }
  | { type: "SET_DIFFICULTY"; difficulty: Difficulty }
  | { type: "UNLOCK_PHONE" }
  | { type: "OPEN_APP"; appId: AppId }
  | { type: "FIND_CLUE"; clueId: ClueId }
  | { type: "EXAMINE_CLUE"; clueId: ClueId }
  | { type: "ZOOM_PHOTO"; photoId: PhotoId }
  | { type: "PLAY_VOICE"; voiceId: VoiceId }
  | { type: "PLAY_VIDEO"; videoId: VideoId }
  | { type: "SOLVE_LOCK"; lockId: LockId }
  | { type: "FAIL_LOCK"; lockId: LockId }
  | { type: "SEE_NOTIFICATION"; notificationId: string }
  | { type: "CHAT_APPEND"; characterId: CharacterId; message: ChatMessage }
  | { type: "CHAT_DISCLOSE"; characterId: CharacterId; factIds: string[] }
  | { type: "CHAT_BEAT"; characterId: CharacterId; beatId: string }
  | { type: "CHAT_INTENT"; characterId: CharacterId; intent: string }
  | { type: "CHAT_PRESENT"; characterId: CharacterId; clueId: ClueId }
  | { type: "CHAT_SILENCE"; characterId: CharacterId; untilMs: number }
  | { type: "CHAT_COLLAPSE"; characterId: CharacterId }
  | { type: "SET_TYPING"; characterId?: CharacterId }
  | { type: "MARK_UNKNOWN_READ" }
  | { type: "LEAK"; token: string }
  | { type: "FIRE_EVENT"; eventId: EventId }
  | { type: "SET_ACCUSATION"; patch: Partial<AccusationDraft> }
  | { type: "RECORD_ACCUSATION"; attempt: AccusationAttempt }
  | { type: "SHOW_REVEAL" }
  | { type: "SEND_AUDIO_TO_DIEGO" }
  | { type: "USE_HINT"; obstacleId: string }
  | { type: "META_ATTEMPT" }
  | { type: "TOUCH_SAVE" };
