/**
 * Device manifest: apps, locks, and clue catalog.
 *
 * This module loads with the initial bundle because the home screen needs it.
 * It therefore contains only neutral labels—no solution text, transcripts, or
 * revelations. Heavy material for Acts 2, 3, and 4 lives in `act2.ts`, `act3.ts`,
 * and `act4.ts`, loaded on demand.
 */

import { normalizeText } from "../engine/text";
import type { Clue, Lock, Memory, PhoneAppDescriptor } from "../engine/types";

export const CASE_DATE = "6 de maio de 2026";

export const APPS: PhoneAppDescriptor[] = [
  { id: "APP_001", name: "Notificações", icon: "Bell", availableFrom: 1, tone: "ambar" },
  { id: "APP_002", name: "Chat", icon: "MessageCircle", availableFrom: 1, tone: "verde" },
  { id: "APP_003", name: "Fotos", icon: "Image", availableFrom: 1, tone: "rosa" },
  { id: "APP_005", name: "Contatos", icon: "Users", availableFrom: 1, tone: "azul" },
  { id: "APP_006", name: "Calendário", icon: "CalendarDays", availableFrom: 1, tone: "roxo" },
  { id: "APP_008", name: "Telefone", icon: "Phone", availableFrom: 1, tone: "verde" },
  { id: "APP_014", name: "Saúde", icon: "Activity", availableFrom: 1, tone: "rosa" },
  { id: "APP_020", name: "Ajustes", icon: "Settings", availableFrom: 1, tone: "cinza" },
  { id: "APP_021", name: "Caderno do Caso", icon: "NotebookPen", availableFrom: 1, tone: "ambar" },

  { id: "APP_004", name: "E-mail", icon: "Mail", availableFrom: 2, tone: "azul" },
  { id: "APP_007", name: "Navegador", icon: "Globe", availableFrom: 2, tone: "azul" },
  { id: "APP_010", name: "Notas", icon: "StickyNote", availableFrom: 2, tone: "ambar" },
  { id: "APP_011", name: "Mapas", icon: "MapPin", availableFrom: 2, tone: "verde" },
  { id: "APP_012", name: "Drive", icon: "CloudUpload", availableFrom: 2, tone: "azul" },
  { id: "APP_013", name: "Lixeira", icon: "Trash2", availableFrom: 2, tone: "cinza" },
  { id: "APP_015", name: "Banco", icon: "Landmark", availableFrom: 2, tone: "verde", lock: "LOCK_007" },
  { id: "APP_016", name: "Corridas", icon: "Car", availableFrom: 2, tone: "cinza" },
  { id: "APP_017", name: "Rede Social", icon: "Hash", availableFrom: 2, tone: "roxo", lock: "LOCK_009" },
  { id: "APP_019", name: "Tarefas", icon: "ListChecks", availableFrom: 2, tone: "verde" },

  { id: "APP_009", name: "Gravador", icon: "Mic", availableFrom: 3, tone: "rosa", lock: "LOCK_004" },
  { id: "APP_018", name: "Autenticador", icon: "KeyRound", availableFrom: 3, tone: "ambar" },
];

/** Apps released as soon as the device is unlocked. */
export const INITIAL_APPS = APPS.map((app) => app.id);

export function appsForAct(act: number) {
  return APPS.filter((app) => app.availableFrom <= act);
}

export function getApp(id: string) {
  return APPS.find((app) => app.id === id);
}

/* ------------------------------------------------------------------ */
/* Locks                                                               */
/* ------------------------------------------------------------------ */

export const LOCKS: Lock[] = [
  {
    id: "LOCK_001",
    kind: "pin",
    prompt: "PIN de 4 dígitos",
    hint: "A mãe de Clara anotou o código num papel dentro da capinha.",
    length: 4,
    accepts: ["0712"],
  },
  {
    id: "LOCK_002",
    kind: "pin",
    prompt: "PIN de 4 dígitos",
    hint: "a data que não acaba",
    length: 4,
    priorAttempts: "Tentativas registradas: 3 falhas em 08/03/2026, 20h24.",
    accepts: ["2206"],
    grantsClues: ["CLUE_011", "CLUE_053"],
  },
  {
    id: "LOCK_003",
    kind: "palavra",
    prompt: "Palavra-chave (minúsculas, sem espaço)",
    hint: "o nome dele",
    accepts: ["wesley"],
    grantsClues: ["CLUE_041", "CLUE_037"],
  },
  {
    id: "LOCK_004",
    kind: "pin",
    prompt: "PIN de 6 dígitos",
    hint: "a data que eu devia ter respeitado",
    length: 6,
    priorAttempts: "Tentativas registradas: 2 falhas em 08/03/2026, 20h29.",
    accepts: ["170498"],
    grantsClues: ["CLUE_010", "CLUE_051"],
  },
  {
    id: "LOCK_005",
    kind: "pergunta",
    prompt: "Qual era o nome do seu primeiro animal de estimação?",
    hint: "Ela guardou a resposta nos Favoritos da galeria.",
    secondFactorPrompt: "Código de verificação (6 dígitos)",
    accepts: ["fumaca", "fumaça"],
    secondFactorAccepts: ["903774", "903 774"],
    grantsClues: ["CLUE_015"],
  },
  {
    id: "LOCK_006",
    kind: "pin",
    prompt: "PIN de 4 dígitos",
    hint: "o dia mais importante do ano",
    length: 4,
    accepts: ["1109"],
    grantsClues: ["CLUE_024"],
  },
  {
    id: "LOCK_007",
    kind: "pin",
    prompt: "Últimos 4 dígitos do CPF da titular",
    hint: "O termo assinado pela família qualifica Clara por extenso.",
    length: 4,
    accepts: ["0698"],
    grantsClues: ["CLUE_014", "CLUE_057", "CLUE_032"],
  },
  {
    id: "LOCK_008",
    kind: "palavra",
    prompt: "Senha do arquivo",
    hint: "onde a gente sempre foi",
    accepts: ["pedralascada", "pedra lascada"],
    grantsClues: ["CLUE_034"],
  },
  {
    id: "LOCK_009",
    kind: "palavra",
    prompt: "Senha da conta",
    hint: "a de sempre + o ano que a gente se conheceu",
    accepts: ["clara2014", "clara 2014"],
    grantsClues: ["CLUE_018", "CLUE_036", "CLUE_043"],
  },
];

export function getLock(id: string) {
  return LOCKS.find((lock) => lock.id === id);
}

/** Tolerant normalization: no accents, lowercase, and no surrounding spaces. */
export const normalizeAnswer = normalizeText;

export function checkLock(lock: Lock, answer: string, secondFactor?: string) {
  const normalized = normalizeAnswer(answer);
  const primaryOk = lock.accepts.some((accepted) => normalizeAnswer(accepted) === normalized);
  if (!primaryOk) return false;
  if (!lock.secondFactorAccepts) return true;
  const secondNormalized = normalizeAnswer(secondFactor ?? "");
  return lock.secondFactorAccepts.some(
    (accepted) => normalizeAnswer(accepted).replace(/\s/g, "") === secondNormalized.replace(/\s/g, ""),
  );
}

/* ------------------------------------------------------------------ */
/* Clue catalog                                                        */
/* ------------------------------------------------------------------ */

export const CLUES: Clue[] = [
  /* Block A—presence at the overlook */
  {
    id: "CLUE_001",
    label: "Notificação das 16h02",
    summary: 'Prévia de mensagem recebida às 16h02 de 08/03: "ai clara…. tá bom. 19h30".',
    app: "APP_001",
    act: 1,
    kind: "fato",
    weight: 3,
    block: "A",
    factEN:
      "A notification preview from 4:02 PM on March 8 shows the best friend accepting a 7:30 PM meeting.",
  },
  {
    id: "CLUE_002",
    label: "Notificação das 18h27",
    summary: 'Prévia de mensagem recebida às 18h27 de 08/03: "to saindo daqui a pouco. me espera lá em cima".',
    app: "APP_001",
    act: 1,
    kind: "fato",
    weight: 4,
    block: "A",
    factEN:
      'A notification preview from 6:27 PM on March 8 reads "I am leaving in a bit, wait for me up there".',
  },
  {
    id: "CLUE_003",
    label: "Lacuna de seis horas",
    summary: "A conversa com a melhor amiga não tem nada entre 14h09 e 20h41 do dia 08/03.",
    app: "APP_002",
    act: 1,
    kind: "fato",
    weight: 3,
    block: "A",
  },
  {
    id: "CLUE_009",
    label: "Faróis às 19h44",
    summary: "Foto do mirante mostra um carro pequeno e vermelho subindo a estrada de acesso.",
    app: "APP_003",
    act: 3,
    kind: "fato",
    weight: 4,
    block: "A",
  },
  {
    id: "CLUE_010",
    label: "Gravação do mirante",
    summary: "Arquivo de 6min12s iniciado às 19h46 de 08/03, no alto do mirante.",
    app: "APP_009",
    act: 3,
    kind: "fato",
    weight: 4,
    block: "A",
  },
  {
    id: "CLUE_023",
    label: 'Compromisso "PL — 19h30"',
    summary: "Evento criado às 15h50 do dia 08/03 para as 19h30 do mesmo dia.",
    app: "APP_006",
    act: 1,
    kind: "fato",
    weight: 2,
    block: "A",
  },
  {
    id: "CLUE_031",
    label: "Carro vermelho da amiga",
    summary: "Foto de dezembro mostra o Renault Kwid vermelho, placa RKA7C21, com adesivo no vidro.",
    app: "APP_003",
    act: 2,
    kind: "fato",
    weight: 3,
    block: "A",
  },
  {
    id: "CLUE_034",
    label: "Backup das 19h30",
    summary: "Cópia automática da conversa feita 28 minutos antes da morte, com as mensagens íntegras.",
    app: "APP_012",
    act: 2,
    kind: "fato",
    weight: 4,
    block: "A",
  },
  {
    id: "CLUE_038",
    label: "Notificação das 15h48",
    summary: 'Prévia da mensagem enviada por Clara: "preciso te falar hoje. pessoalmente. pedra lasc…".',
    app: "APP_001",
    act: 1,
    kind: "fato",
    weight: 2,
    block: "A",
  },

  /* Block B—time of death and device use */
  {
    id: "CLUE_004",
    label: "Última leitura cardíaca",
    summary: "Frequência cardíaca registrada até 19h58 e alerta de queda detectada no mesmo minuto.",
    app: "APP_014",
    act: 1,
    kind: "fato",
    weight: 4,
    block: "B",
    factEN: "The wrist band recorded a final heart rate at 7:58 PM and logged a fall alert at the same minute.",
  },
  {
    id: "CLUE_004B",
    label: "Escalada de 80 para 118 bpm",
    summary: "Entre 19h44 e 19h57 a frequência cardíaca sobe de 80 para 118 batimentos.",
    app: "APP_014",
    act: 1,
    kind: "fato",
    weight: 3,
    block: "B",
  },
  {
    id: "CLUE_005",
    label: "Uso do aparelho após 19h58",
    summary: "Relatório de tempo de tela mostra o telefone desbloqueado e ativo entre 20h11 e 21h20.",
    app: "APP_020",
    act: 1,
    kind: "fato",
    weight: 4,
    block: "B",
    factEN: "The screen time report shows the phone unlocked and in use between 8:11 PM and 9:20 PM.",
  },
  {
    id: "CLUE_006",
    label: "Localização imóvel",
    summary: "O aparelho ficou parado no mirante das 19h31 até 06h32 do dia seguinte.",
    app: "APP_011",
    act: 2,
    kind: "fato",
    weight: 4,
    block: "B",
  },
  {
    id: "CLUE_007",
    label: '"cheguei em casa" às 20h41',
    summary: "Mensagem enviada às 20h41 afirmando que Clara chegou em casa, com o aparelho ainda no mirante.",
    app: "APP_002",
    act: 1,
    kind: "inferencial",
    weight: 4,
    block: "B",
  },
  {
    id: "CLUE_007B",
    label: "Mensagem das 20h47",
    summary: '"mãe, tô bem. só preciso ficar sozinha hoje" — enviada às 20h47.',
    app: "APP_002",
    act: 1,
    kind: "fato",
    weight: 3,
    block: "B",
  },
  {
    id: "CLUE_007C",
    label: "Mensagem das 21h13",
    summary: '"não vem aqui hj. amanhã eu te explico tudo" — enviada às 21h13.',
    app: "APP_002",
    act: 1,
    kind: "fato",
    weight: 3,
    block: "B",
  },
  {
    id: "CLUE_051",
    label: "Falhas no gravador às 20h29",
    summary: "O aplicativo de gravação registrou 2 tentativas de senha erradas às 20h29 de 08/03.",
    app: "APP_009",
    act: 1,
    kind: "fato",
    weight: 3,
    block: "B",
  },
  {
    id: "CLUE_053",
    label: "Falhas nas notas às 20h24",
    summary: "O aplicativo de notas registrou 3 tentativas de senha erradas às 20h24 de 08/03.",
    app: "APP_010",
    act: 1,
    kind: "fato",
    weight: 3,
    block: "B",
  },
  {
    id: "CLUE_060",
    label: "Índice de fotos intacto",
    summary: "O contador interno da galeria bate com a última foto salva: nada foi apagado naquela noite.",
    app: "APP_020",
    act: 2,
    kind: "fato",
    weight: 1,
    block: "B",
  },
  {
    id: "CLUE_066",
    label: "Quem sabia o PIN",
    summary: 'Nota "pro caso de": o PIN é o aniversário de Clara e uma única pessoa sabe disso desde 2019.',
    app: "APP_010",
    act: 1,
    kind: "fato",
    weight: 4,
    block: "B",
  },

  /* Block C—motive */
  {
    id: "CLUE_011",
    label: "Nota trancada 22/06",
    summary: "Diário fragmentado escrito desde junho de 2025, interrompido no meio da última frase.",
    app: "APP_010",
    act: 2,
    kind: "fato",
    weight: 4,
    block: "C",
  },
  {
    id: "CLUE_012",
    label: "Farol quebrado",
    summary: "Foto de 22/06/2025 mostra o canto dianteiro direito de um Fit prata destruído.",
    app: "APP_003",
    act: 2,
    kind: "fato",
    weight: 3,
    block: "C",
  },
  {
    id: "CLUE_013",
    label: "Matéria do Tribuna do Vale",
    summary: "Captura de tela sobre um motociclista morto atropelado em 22/06/2025.",
    app: "APP_003",
    act: 2,
    kind: "fato",
    weight: 3,
    block: "C",
  },
  {
    id: "CLUE_014",
    label: "Pix mensais de R$ 400",
    summary: "Nove transferências mensais para a mesma destinatária, desde julho de 2025.",
    app: "APP_015",
    act: 2,
    kind: "fato",
    weight: 3,
    block: "C",
  },
  {
    id: "CLUE_015",
    label: "E-mails com a criminalista",
    summary: "Sete mensagens trocadas com uma advogada entre 09/02 e 02/03 de 2026.",
    app: "APP_004",
    act: 3,
    kind: "fato",
    weight: 4,
    block: "C",
  },
  {
    id: "CLUE_016",
    label: "Tarefa de segunda-feira",
    summary: '"SEG 9h — Dra. Yara — LEVAR O ÁUDIO E A NOTA", criada em 02/03.',
    app: "APP_019",
    act: 2,
    kind: "fato",
    weight: 3,
    block: "C",
  },
  {
    id: "CLUE_017",
    label: "Nota fiscal da funilaria",
    summary: "Serviço 2214, de 24/06/2025, para um Honda Fit prata, pago em espécie.",
    app: "APP_003",
    act: 2,
    kind: "fato",
    weight: 3,
    block: "C",
  },
  {
    id: "CLUE_022",
    label: "Pesquisas jurídicas",
    summary: "Buscas sobre omissão de socorro, apresentação espontânea e pena por fuga do local.",
    app: "APP_007",
    act: 2,
    kind: "fato",
    weight: 2,
    block: "C",
  },
  {
    id: "CLUE_024",
    label: "Álbum oculto",
    summary: "Duas fotos da madrugada de 22/06/2025, tiradas de dentro do carro em movimento.",
    app: "APP_003",
    act: 3,
    kind: "fato",
    weight: 4,
    block: "C",
  },
  {
    id: "CLUE_039",
    label: "A entrega de 21/06",
    summary: "Conversa de entrega banal com o mesmo entregador, três horas antes do atropelamento.",
    app: "APP_002",
    act: 2,
    kind: "fato",
    weight: 2,
    block: "C",
  },
  {
    id: "CLUE_041",
    label: "Declaração de 08/03",
    summary: "Documento escrito por Clara na manhã do dia em que morreu, para entregar à advogada.",
    app: "APP_012",
    act: 3,
    kind: "fato",
    weight: 4,
    block: "C",
  },
  {
    id: "CLUE_043",
    label: "Ato de seis meses",
    summary: "Convite e stories de dezembro ligam Clara à família da vítima do atropelamento.",
    app: "APP_017",
    act: 2,
    kind: "fato",
    weight: 2,
    block: "C",
  },
  {
    id: "CLUE_050",
    label: "Pesquisas de 22/06/2025",
    summary: '"o que acontece com quem foge de atropelamento" e "eu posso ser presa se eu não denunciar".',
    app: "APP_007",
    act: 2,
    kind: "fato",
    weight: 3,
    block: "C",
  },
  {
    id: "CLUE_054",
    label: "Local visitado uma única vez",
    summary: "Av. Barão do Cristal aparece nos locais frequentes com uma visita: 22/06/2025, 02h47.",
    app: "APP_011",
    act: 2,
    kind: "fato",
    weight: 4,
    block: "C",
  },
  {
    id: "CLUE_057",
    label: "Saque de R$ 1.850",
    summary: "Retirada em espécie feita em 24/06/2025, no valor exato do conserto.",
    app: "APP_015",
    act: 2,
    kind: "fato",
    weight: 3,
    block: "C",
  },

  /* Block D—coercion and relationship */
  {
    id: "CLUE_025",
    label: 'O apelido "Cacau"',
    summary: "Em todo o aparelho, uma única pessoa chama Clara assim.",
    app: "APP_002",
    act: 1,
    kind: "fato",
    weight: 4,
  },
  {
    id: "CLUE_032",
    label: "Dinheiro recebido da amiga",
    summary: "R$ 1.200 em janeiro e R$ 800 em fevereiro, ambos recusados por Clara.",
    app: "APP_015",
    act: 2,
    kind: "fato",
    weight: 2,
  },
  {
    id: "CLUE_045",
    label: 'Compromisso "A. — shopping"',
    summary: "Encontro de 52 minutos em 05/03, criado no dia anterior.",
    app: "APP_006",
    act: 2,
    kind: "fato",
    weight: 2,
  },
  {
    id: "CLUE_047",
    label: "Pesquisa sobre coação",
    summary: '"amiga me ameaçando indiretamente é crime" e "coação no curso do processo art 344", em 05/03.',
    app: "APP_007",
    act: 2,
    kind: "fato",
    weight: 3,
  },
  {
    id: "CLUE_055",
    label: "Nota apagada de 05/03",
    summary: '"hoje eu conto pra Lice. se der ruim, tá tudo escrito na outra nota."',
    app: "APP_013",
    act: 2,
    kind: "fato",
    weight: 3,
  },
  {
    id: "CLUE_058",
    label: "Tarefa riscada",
    summary: '"apagar o áudio", criada às 22h10 de 05/03 e nunca concluída.',
    app: "APP_019",
    act: 2,
    kind: "fato",
    weight: 3,
  },
  {
    id: "CLUE_061",
    label: "Mensagem de 22/06/2025",
    summary: "O namorado escreve, na manhã seguinte à festa, quem lhe devolveu o carro amassado.",
    app: "APP_002",
    act: 1,
    kind: "fato",
    weight: 4,
  },
  {
    id: "CLUE_062",
    label: "O pedido do saque",
    summary: '"ninguém vai olhar pra sua conta" — mensagem de 24/06/2025.',
    app: "APP_002",
    act: 1,
    kind: "fato",
    weight: 3,
  },
  {
    id: "CLUE_068",
    label: "Ligação de 22 minutos",
    summary: "Chamada recebida às 03h58 de 22/06/2025, uma hora depois do atropelamento.",
    app: "APP_008",
    act: 2,
    kind: "fato",
    weight: 3,
  },
  {
    id: "CLUE_059",
    label: "Rede Wi-Fi salva",
    summary: "Uma das redes memorizadas leva o sobrenome de uma das pessoas próximas.",
    app: "APP_020",
    act: 3,
    kind: "fato",
    weight: 1,
  },

  /* Block E—anonymous contact identity */
  {
    id: "CLUE_028",
    label: "Ligação de 3 segundos",
    summary: "Chamada efetuada às 21h18 de 08/03 para um número sem cadastro.",
    app: "APP_008",
    act: 1,
    kind: "fato",
    weight: 4,
  },
  {
    id: "CLUE_026",
    label: "O apelido, de novo",
    summary: "O contato anônimo usa um apelido que ninguém fora do círculo íntimo conhecia.",
    app: "APP_002",
    act: 3,
    kind: "testemunhal",
    weight: 4,
  },
  {
    id: "CLUE_027",
    label: "O casaco na mureta",
    summary: "O contato anônimo descreve um detalhe do local que nunca foi divulgado.",
    app: "APP_002",
    act: 3,
    kind: "testemunhal",
    weight: 4,
  },
  {
    id: "CLUE_029",
    label: "Tiques de escrita",
    summary: "Duas conversas diferentes repetem exatamente os mesmos vícios de digitação.",
    app: "APP_002",
    act: 3,
    kind: "inferencial",
    weight: 3,
  },
  {
    id: "CLUE_030",
    label: "Nunca ao mesmo tempo",
    summary: "As duas janelas jamais aparecem digitando no mesmo instante.",
    app: "APP_002",
    act: 3,
    kind: "inferencial",
    weight: 3,
  },
  {
    id: "CLUE_040",
    label: "O valor exato",
    summary: "O contato anônimo cita um valor que só aparece em documentos particulares de Clara.",
    app: "APP_002",
    act: 3,
    kind: "testemunhal",
    weight: 3,
  },
  {
    id: "CLUE_064",
    label: "A pergunta repetida",
    summary: "Só uma pessoa em toda a investigação quer saber se existem gravações.",
    app: "APP_002",
    act: 3,
    kind: "testemunhal",
    weight: 3,
  },
  {
    id: "CLUE_065",
    label: "A concessão",
    summary: 'Pressionado sobre a fonte do valor, o contato anônimo responde: "a Clara me contou".',
    app: "APP_002",
    act: 3,
    kind: "testemunhal",
    weight: 4,
  },
  {
    id: "CLUE_069",
    label: "Data de ativação da linha",
    summary: "O número anônimo foi ativado em 12/02/2026, três semanas antes da morte.",
    app: "APP_021",
    act: 4,
    kind: "fato",
    weight: 4,
  },
  {
    id: "CLUE_074",
    label: "A versão oferecida",
    summary: "Uma entrevistada oferece, sem ser perguntada, um caminho de suspeita contra outra pessoa.",
    app: "APP_002",
    act: 3,
    kind: "testemunhal",
    weight: 3,
  },

  /* Block F—context, noise, and red herrings */
  {
    id: "CLUE_008",
    label: "Três chamadas perdidas",
    summary: "A mãe ligou às 21h35, 22h02 e 22h40 do dia 08/03. Nenhuma foi atendida.",
    app: "APP_008",
    act: 1,
    kind: "fato",
    weight: 2,
  },
  {
    id: "CLUE_018",
    label: "Mensagens do irmão",
    summary: "Seis mensagens diretas, entre 03/02 e 06/03, de tom crescente.",
    app: "APP_017",
    act: 2,
    kind: "fato",
    weight: 3,
  },
  {
    id: "CLUE_019",
    label: "Corridas de 08/03",
    summary: "Vinte e sete corridas registradas entre 17h02 e 01h41, do outro lado da cidade.",
    app: "APP_016",
    act: 3,
    kind: "testemunhal",
    weight: 4,
  },
  {
    id: "CLUE_020",
    label: "Conta em nome de terceiro",
    summary: "O cabeçalho do aplicativo de corridas não traz o nome de quem dirige.",
    app: "APP_016",
    act: 3,
    kind: "testemunhal",
    weight: 2,
  },
  {
    id: "CLUE_021",
    label: "Áudio das 08h12",
    summary: '"hoje eu resolvo isso" — mensagem de voz enviada à mãe na manhã de 08/03.',
    app: "APP_002",
    act: 1,
    kind: "fato",
    weight: 3,
  },
  {
    id: "CLUE_033",
    label: "A resposta de janeiro",
    summary: '"Esquece isso, minha filha." — troca de mensagens de madrugada em 05/01/2026.',
    app: "APP_002",
    act: 1,
    kind: "fato",
    weight: 3,
  },
  {
    id: "CLUE_036",
    label: "Transmissão ao vivo",
    summary: "Print de uma live de 19h20 às 20h05 do dia 08/03, a cem quilômetros da cidade.",
    app: "APP_017",
    act: 2,
    kind: "fato",
    weight: 4,
  },
  {
    id: "CLUE_037",
    label: "Envio às 09h51",
    summary: "Notificação de upload de um documento para uma pasta protegida, na manhã de 08/03.",
    app: "APP_001",
    act: 1,
    kind: "fato",
    weight: 2,
  },
  {
    id: "CLUE_042",
    label: "Aviso de espaço cheio",
    summary: "E-mail de 04/03 informando que a nuvem estava em 14,6 GB de 15 GB.",
    app: "APP_004",
    act: 2,
    kind: "fato",
    weight: 1,
  },
  {
    id: "CLUE_044",
    label: "Recorrência mensal",
    summary: 'Evento "Pix M." repetido todo dia 2, desde julho de 2025.',
    app: "APP_006",
    act: 2,
    kind: "fato",
    weight: 2,
  },
  {
    id: "CLUE_046",
    label: "Consulta de 09/03",
    summary: "Compromisso marcado para as 9h da manhã seguinte à morte.",
    app: "APP_006",
    act: 1,
    kind: "fato",
    weight: 3,
  },
  {
    id: "CLUE_048",
    label: "Desbloqueio de madrugada",
    summary: "Alguém abriu o aparelho às 03h12 de 14/02 e usou o aplicativo do banco por 6 minutos.",
    app: "APP_020",
    act: 2,
    kind: "fato",
    weight: 2,
  },
  {
    id: "CLUE_049",
    label: "Perfil visitado",
    summary: "Navegação no perfil do irmão da vítima em 20/12/2025.",
    app: "APP_007",
    act: 2,
    kind: "fato",
    weight: 1,
  },
  {
    id: "CLUE_052",
    label: "Nota vazia",
    summary: 'Uma nota sem conteúdo, com o título "NÃO ESQUECER 22/06".',
    app: "APP_010",
    act: 2,
    kind: "fato",
    weight: 2,
  },
  {
    id: "CLUE_056",
    label: "Despertar recorrente",
    summary: "Cento e dezessete noites acordando sempre às 02h41.",
    app: "APP_014",
    act: 2,
    kind: "fato",
    weight: 2,
  },
  {
    id: "CLUE_063",
    label: "O aviso",
    summary: "Um dos entrevistados avisa que ligou para outra pessoa depois de falar com você.",
    app: "APP_002",
    act: 3,
    kind: "testemunhal",
    weight: 2,
  },
  {
    id: "CLUE_067",
    label: "Furos do arquivamento",
    summary: "O despacho oficial contém quatro afirmações contrariadas pelos dados do aparelho.",
    app: "APP_012",
    act: 2,
    kind: "inferencial",
    weight: 3,
  },
  {
    id: "CLUE_035",
    label: "Rascunho não enviado",
    summary: "Uma carta escrita em 07/03 e apagada 28 minutos depois.",
    app: "APP_013",
    act: 2,
    kind: "fato",
    weight: 3,
  },
  {
    id: "CLUE_070",
    label: "O gesto na mesa",
    summary: "Foto em movimento de 08/03, 11h52: uma mão avança e cobre a lente. Três segundos, sem som.",
    app: "APP_003",
    act: 2,
    kind: "fato",
    weight: 4,
  },
  {
    id: "CLUE_071",
    label: "Áudio recuperado de 05/01",
    summary: "Mensagem de voz de 2:14 enviada às 02h31, expirada no servidor e recuperada do aparelho.",
    app: "APP_013",
    act: 2,
    kind: "fato",
    weight: 4,
  },
  {
    id: "CLUE_072",
    label: "Escala do plantão de março",
    summary: "Folha afixada na geladeira, com uma troca de horário anotada à caneta para o dia 08.",
    app: "APP_003",
    act: 2,
    kind: "fato",
    weight: 3,
  },
  {
    id: "CLUE_073",
    label: "Folha de ponto do hospital",
    summary: "Ofício com registro de catraca, acessos ao prontuário e medicações da noite de 08/03.",
    app: "APP_012",
    act: 3,
    kind: "fato",
    weight: 4,
  },
  {
    id: "CLUE_075",
    label: "Nota das 12h14",
    summary: "Anotação escrita por Clara depois do almoço de 08/03, sobre a conversa com a mãe.",
    app: "APP_010",
    act: 2,
    kind: "fato",
    weight: 4,
  },
  {
    id: "CLUE_076",
    label: "O carro na garagem",
    summary: "Foto de 08/03, 12h04: um hatch vermelho-escuro antigo parado no quintal, placa parcial.",
    app: "APP_003",
    act: 2,
    kind: "fato",
    weight: 2,
  },
];

const CLUE_INDEX = new Map(CLUES.map((clue) => [clue.id, clue]));

export function getClue(id: string) {
  return CLUE_INDEX.get(id);
}

export function isKnownClue(id: string) {
  return CLUE_INDEX.has(id);
}

/* ------------------------------------------------------------------ */
/* Deductions                                                          */
/* ------------------------------------------------------------------ */

export const MEMORIES: Memory[] = [
  {
    id: "MEMORY_001",
    label: "Vinte e um minutos",
    text: "O coração de Clara parou às 19h58. O aparelho foi desbloqueado às 20h11.",
    requiresAllOf: ["CLUE_004"],
    requiresAnyOf: ["CLUE_005", "CLUE_006", "CLUE_007"],
    requiresCount: 1,
  },
  {
    id: "MEMORY_002",
    label: "Ela estava no carro",
    text: "Clara esteve na Avenida Barão do Cristal na madrugada de 22 de junho de 2025.",
    requiresAnyOf: ["CLUE_011", "CLUE_054", "CLUE_024"],
    requiresCount: 1,
  },
  {
    id: "MEMORY_003",
    label: "O dinheiro",
    text: "Clara pagava a família da vítima todo mês e financiou o conserto do carro.",
    requiresAnyOf: ["CLUE_014", "CLUE_057", "CLUE_017"],
    requiresCount: 2,
  },
  {
    id: "MEMORY_004",
    label: "Quem estava ao volante",
    text: "Quem dirigia o carro na madrugada de 22/06/2025 não era o dono do veículo.",
    requiresAnyOf: ["CLUE_010", "CLUE_024", "CLUE_041", "CLUE_061"],
    requiresCount: 2,
  },
  {
    id: "MEMORY_005",
    label: "Alguém subiu o mirante",
    text: "Uma segunda pessoa chegou ao mirante entre 19h44 e 19h47 de 08/03.",
    requiresAnyOf: ["CLUE_002", "CLUE_009", "CLUE_010", "CLUE_034"],
    requiresCount: 2,
  },
  {
    id: "MEMORY_007",
    label: "Havia um prazo",
    text: "Clara tinha hora marcada para as 9h da manhã seguinte à própria morte.",
    requiresAnyOf: ["CLUE_015", "CLUE_016", "CLUE_046"],
    requiresCount: 2,
  },
  {
    id: "MEMORY_009",
    label: "A mesma pessoa",
    text: "O contato anônimo sabe coisas que só alguém presente no mirante poderia saber.",
    requiresAnyOf: ["CLUE_026", "CLUE_027", "CLUE_029", "CLUE_065"],
    requiresCount: 2,
  },
  {
    id: "MEMORY_011",
    label: "Duas pessoas sabiam o código",
    text: "Só duas pessoas no mundo conheciam o PIN da tela — e uma delas estava morta.",
    requiresAllOf: ["CLUE_066"],
    requiresAnyOf: ["CLUE_005", "CLUE_053", "CLUE_051"],
    requiresCount: 1,
  },
  {
    id: "MEMORY_012",
    label: "O inquérito de cinco semanas",
    text: "O despacho de arquivamento se apoia em quatro afirmações que os dados desmentem.",
    requiresAllOf: ["CLUE_067"],
  },
  {
    id: "MEMORY_013",
    label: "O que a mãe sabia",
    text: "Regina soube em 5 de janeiro que houve uma morte — e pediu silêncio.",
    requiresAllOf: ["CLUE_071"],
    requiresAnyOf: ["CLUE_033", "CLUE_075"],
    requiresCount: 1,
  },
  {
    id: "MEMORY_014",
    label: "Doze horas de plantão",
    text: "O ponto biométrico registra entrada às 18h50 de 08/03 e nenhuma saída até as 07h10.",
    requiresAllOf: ["CLUE_073"],
  },
  {
    id: "MEMORY_015",
    label: "Dois carros vermelhos",
    text: "O carro que subiu a estrada do mirante às 19h44 não tem a placa do carro da garagem.",
    requiresAllOf: ["CLUE_009", "CLUE_076"],
  },
];

/** Contradictions detected automatically after both clues are examined. */
export const CONTRADICTIONS: Array<{ id: string; pair: [string, string]; text: string }> = [
  {
    id: "CONTRA_01",
    pair: ["CLUE_006", "CLUE_007"],
    text: "O aparelho estava no mirante quando a mensagem “cheguei em casa” foi enviada.",
  },
  {
    id: "CONTRA_02",
    pair: ["CLUE_004", "CLUE_005"],
    text: "O coração parou às 19h58, mas o telefone foi usado até 21h20.",
  },
  {
    id: "CONTRA_03",
    pair: ["CLUE_004", "CLUE_007C"],
    text: "A última mensagem enviada é 75 minutos posterior à última batida registrada.",
  },
  {
    id: "CONTRA_04",
    pair: ["CLUE_002", "CLUE_003"],
    text: "Existe notificação de uma mensagem que não existe mais na conversa.",
  },
  {
    id: "CONTRA_05",
    pair: ["CLUE_018", "CLUE_036"],
    text: "Quem ameaçava Clara estava transmitindo ao vivo a cem quilômetros na hora da morte.",
  },
  {
    id: "CONTRA_06",
    pair: ["CLUE_028", "CLUE_069"],
    text: "O número anônimo já existia — e foi discado do próprio aparelho de Clara às 21h18.",
  },
  {
    id: "CONTRA_07",
    pair: ["CLUE_072", "CLUE_008"],
    text: "A escala tinha uma troca anotada para as 22h, e as chamadas da mãe começam às 21h35.",
  },
  {
    id: "CONTRA_08",
    pair: ["CLUE_072", "CLUE_073"],
    text: "A troca de plantão foi pedida em 06/03 e indeferida em 07/03. O ponto não registra saída.",
  },
  {
    id: "CONTRA_09",
    pair: ["CLUE_075", "CLUE_046"],
    text: "Clara falou de advogada no almoço, e às 15h06 a resposta pergunta duas vezes que doutora.",
  },
];
